"""Add available to market

Revision ID: 5d57aa171d21
Revises: cdaf67e2e845
Create Date: 2024-02-10 08:04:15.055050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d57aa171d21'
down_revision = 'cdaf67e2e845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
